### ISSUE TITLE
About TestWebApp

### ISSUE THREAD

**Issue by rafakwolf** [yurikolesnikov/nlog.webviewer#1]
Hello...

I'm trying to test your library, but the TestWebApp shows http 404.

Thanks

**Comment by yurikolesnikov** [comment]
In TestWebApp log viewer is configured to _Logs_ path (in web,config).
So in order to veiw logs following url could be used in test app: [http://localhost:53612/Logs](http://localhost:53612/Logs)
I added into TestWebApp index.html with link to logs (and short description from readme).

**Comment by rafakwolf** [comment]
OK, thanks for your attention
